import './modules/description'
import './modules/faq'
import './modules/slider'
import './modules/decor'
import './modules/modal'
import './modules/tabs'
import './modules/select-curency'
import './modules/select'
import './modules/payment-method'
import './modules/reviews'
import './modules/rating'
import './modules/profile-control'
import './modules/calc-switch'
import './modules/countries-list'
import './modules/footer'

